### ISSUE TITLE
GitHub actions is broken after merge

### ISSUE THREAD

**Issue by efren-cabrera** [andrea-sanchez/color-generator#14]
We need to update GitHub actions workflow

**Comment by andrea-sanchez** [comment]
This _issue_ was resolved by @efren-cabrera 
Apparently, when merging the _pull requests_ above, I forgot to chance in `.github/workflows/publishDockerImage.yml` the name of the repository, and it caused a break in the construction of the image. As a note, we have different repository names.
The change and solution can be seen in the [link](https://github.com/andrea-sanchez/color_generator/pull/15/commits/1dc71c53e0affb3d19534e984226f5bf2640d131)
